console.log("Hey What's up, Hope you're doing well. Here is your Business Name Generated by our Portal")
let adjective = Math.random();
let shop_name = Math.random();
let last_word = Math.random();
let prefix;
let main;
let suffix;
if (adjective<=0.3333334) {
    prefix = "Crazy";
}
else if(adjective>=0.6666663){
    prefix = "Fire";
}
else{
    prefix = "Amazing";
}
if (last_word<=0.3333334) {
    suffix = "Hub";
} else if(last_word>=0.6666663){
    suffix = "limited";
}
else{
    suffix = "bros";
}
if (shop_name<=0.3333334) {
    main = "Food";
}
else if(shop_name>=0.6666663){
    main = "Engine";
}
else{
    main = "Garments";
}
//console.log("\nFor Automobile Sector Business:-\n '", prefix, "Engine", suffix, "'");//ye mera moderation h
//console.log("\nFor Food Sector Business:-\n '", prefix, "Food", suffix, "'");
//console.log("\nFor Automobile Sector Business:-\n '", prefix, "Garments", suffix, "'");
console.log(` Business Name is :-\n'${prefix} ${main} ${suffix}'`);